package com.nidoham.server.manager

import androidx.paging.Pager
import androidx.paging.PagingConfig
import androidx.paging.PagingData
import androidx.paging.PagingSource
import androidx.paging.PagingState
import com.google.firebase.Timestamp
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.DocumentSnapshot
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.ListenerRegistration
import com.google.firebase.firestore.Query
import com.nidoham.server.domain.message.Conversation
import com.nidoham.server.domain.participant.Participant
import com.nidoham.server.util.ParticipantRole
import com.nidoham.server.util.ParticipantType
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await

/**
 * Manages all Conversation-related Firestore operations.
 *
 * Firestore schema:
 *   conversations/{conversationId}               — Conversation document
 *   participant/{conversationId}/member/{userId}  — Participant sub-collection
 *
 * Every operation that targets a specific conversation is keyed by [conversationId].
 * Operations that involve a participant are additionally keyed by [userId].
 *
 * @param firestore Injectable [FirebaseFirestore] instance.
 * @param auth      Injectable [FirebaseAuth] instance.
 */
class ConversationManager(
    private val firestore: FirebaseFirestore = FirebaseFirestore.getInstance(),
    private val auth: FirebaseAuth = FirebaseAuth.getInstance()
) {

    companion object {
        private const val CONVERSATION_COLLECTION = "conversations"
        private const val PARTICIPANT_ROOT        = "participant"
        private const val PARTICIPANT_SUB         = "member"          // participant/{conversationId}/member/{userId}
        private const val PAGE_SIZE               = 20

        private const val FIELD_UID               = "uid"
        private const val FIELD_PARENT_ID         = "parent_id"
        private const val FIELD_TYPE              = "type"
        private const val FIELD_CREATOR_ID        = "creator_id"
        private const val FIELD_TITLE             = "title"
        private const val FIELD_LAST_MESSAGE      = "last_message"
        private const val FIELD_UPDATED_AT        = "updated_at"
        private const val FIELD_CREATED_AT        = "created_at"
        private const val FIELD_SUBSCRIBER_COUNT  = "subscriber_count"
        private const val FIELD_MESSAGE_COUNT     = "message_count"
        private const val FIELD_TRANSLATED        = "translated"
    }

    // ─────────────────────────────────────────────────────────────────────────
    // References
    // ─────────────────────────────────────────────────────────────────────────

    private fun conversationsCollection() =
        firestore.collection(CONVERSATION_COLLECTION)

    private fun conversationDocument(conversationId: String) =
        conversationsCollection().document(conversationId)

    private fun participantDocument(conversationId: String, userId: String) =
        firestore.collection(PARTICIPANT_ROOT)
            .document(conversationId)
            .collection(PARTICIPANT_SUB)
            .document(userId)

    // ─────────────────────────────────────────────────────────────────────────
    // Write Operations
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Creates a new [Conversation] document and atomically adds the currently
     * authenticated user as the sole initial participant in a single batch write.
     *
     * The conversation's [Conversation.id] is auto-generated by Firestore and
     * written back into the document. The current user is assigned the
     * [ParticipantRole.ADMIN] role, since they are the creator. The participant
     * type mirrors the conversation type (personal vs. group).
     *
     * @param conversation The [Conversation] object to persist. The [Conversation.id]
     *                     field may be left blank; it will be assigned automatically.
     * @return The auto-generated conversation ID on success.
     */
    suspend fun createConversation(conversation: Conversation): Result<String> = runCatching {
        val currentUser = auth.currentUser
            ?: error("No authenticated user is signed in.")

        val docRef = if (conversation.id.isBlank()) {
            conversationsCollection().document()
        } else {
            conversationDocument(conversation.id)
        }

        val conversationId = docRef.id
        val populated      = conversation.copy(id = conversationId, creatorId = currentUser.uid)

        val participantRef = participantDocument(conversationId, currentUser.uid)
        val participant    = Participant(
            uid      = currentUser.uid,
            parentId = conversationId,           // fixed: was id = conversationId
            role     = ParticipantRole.ADMIN.value,
            type     = conversation.type
        )

        firestore.batch().apply {
            set(docRef, populated)
            set(participantRef, participant)
        }.commit().await()

        conversationId
    }

    /**
     * Updates specific fields of an existing [Conversation] document. Automatically
     * stamps [FIELD_UPDATED_AT] with the current server time if not already included
     * in [fields].
     *
     * @param conversationId The conversation document ID.
     * @param fields         Map of Firestore field names to their new values.
     */
    suspend fun updateConversation(
        conversationId: String,
        fields: Map<String, Any?>
    ): Result<Unit> = runCatching {
        require(fields.isNotEmpty()) { "Update fields must not be empty." }
        val stamped = if (FIELD_UPDATED_AT !in fields) {
            fields + (FIELD_UPDATED_AT to com.google.firebase.firestore.FieldValue.serverTimestamp())
        } else fields
        conversationDocument(conversationId).update(stamped).await()
    }

    /**
     * Updates the last message preview on a conversation document. Typically
     * called after a message is successfully sent.
     *
     * @param conversationId The conversation document ID.
     * @param preview        The content string to store as the last message preview.
     */
    suspend fun updateLastMessage(
        conversationId: String,
        preview: String
    ): Result<Unit> = updateConversation(
        conversationId,
        mapOf(FIELD_LAST_MESSAGE to preview)
    )

    /**
     * Increments [FIELD_MESSAGE_COUNT] by 1 using a Firestore atomic increment.
     *
     * @param conversationId The conversation document ID.
     */
    suspend fun incrementMessageCount(conversationId: String): Result<Unit> =
        updateConversation(
            conversationId,
            mapOf(FIELD_MESSAGE_COUNT to com.google.firebase.firestore.FieldValue.increment(1))
        )

    /**
     * Decrements [FIELD_MESSAGE_COUNT] by 1 using a Firestore atomic increment.
     *
     * @param conversationId The conversation document ID.
     */
    suspend fun decrementMessageCount(conversationId: String): Result<Unit> =
        updateConversation(
            conversationId,
            mapOf(FIELD_MESSAGE_COUNT to com.google.firebase.firestore.FieldValue.increment(-1))
        )

    /**
     * Permanently deletes a conversation document. This does not cascade-delete
     * its messages sub-collection; call [MessageManager.deleteAllMessages] first
     * if a full wipe is required.
     *
     * @param conversationId The conversation document ID to delete.
     */
    suspend fun deleteConversation(conversationId: String): Result<Unit> = runCatching {
        conversationDocument(conversationId).delete().await()
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Read Operations
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Fetches a single [Conversation] document by its ID.
     *
     * @return The [Conversation] object, or null if it does not exist.
     */
    suspend fun fetchConversation(conversationId: String): Result<Conversation?> = runCatching {
        conversationDocument(conversationId)
            .get()
            .await()
            .toObject(Conversation::class.java)
    }

    /**
     * Fetches all conversations in which a given user is a participant by
     * performing a collection group query on the member sub-collection and
     * resolving each parent conversation document.
     *
     * The conversation ID is read from the stored [FIELD_PARENT_ID] field rather
     * than derived from the document path, ensuring correctness regardless of
     * nesting depth.
     *
     * Requires a composite Firestore index on (uid, type) in the member
     * collection group.
     *
     * @param userId The Firebase UID of the user whose conversations to retrieve.
     * @param type   Participant type filter; defaults to [ParticipantType.PERSONAL].
     * @return A list of [Conversation] objects the user is a member of.
     */
    suspend fun fetchConversationsForUser(
        userId: String,
        type: ParticipantType = ParticipantType.PERSONAL
    ): Result<List<Conversation>> = runCatching {
        val conversationIds = firestore.collectionGroup(PARTICIPANT_SUB)
            .whereEqualTo(FIELD_UID, userId)
            .whereEqualTo(FIELD_TYPE, type.value)
            .get()
            .await()
            .documents
            .mapNotNull { it.getString(FIELD_PARENT_ID) }   // fixed: read field, not path

        conversationIds
            .map { conversationDocument(it).get().await() }
            .mapNotNull { it.toObject(Conversation::class.java) }
    }

    /**
     * Fetches conversations for the currently authenticated user.
     *
     * @param type Participant type filter; defaults to [ParticipantType.PERSONAL].
     */
    suspend fun fetchCurrentUserConversations(
        type: ParticipantType = ParticipantType.PERSONAL
    ): Result<List<Conversation>> {
        val currentUserId = auth.currentUser?.uid
            ?: return Result.failure(IllegalStateException("No authenticated user is signed in."))
        return fetchConversationsForUser(currentUserId, type)
    }

    /**
     * Applies a [ConversationFilter] to the conversations collection and returns
     * all matching records as a plain list.
     *
     * @param filter The [ConversationFilter] describing the desired constraints.
     */
    suspend fun fetchConversationsFiltered(
        filter: ConversationFilter
    ): Result<List<Conversation>> = runCatching {
        filter.applyTo(conversationsCollection())
            .get()
            .await()
            .toObjects(Conversation::class.java)
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Search Operations
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Searches conversations whose [title] field starts with the given [prefix],
     * optionally narrowed by [ConversationFilter].
     *
     * Firestore does not support native full-text search. This method uses a
     * lexicographic range query — [whereGreaterThanOrEqualTo] paired with
     * [whereLessThanOrEqualTo] against the Unicode sentinel `\uf8ff` — which
     * matches all strings that begin with [prefix]. The query is case-sensitive;
     * pass a lowercased [prefix] and store titles in lowercase if case-insensitive
     * matching is required.
     *
     * A single-field ascending index on `title` is required. If [filter] also
     * orders or filters on a second field, a composite index will be needed.
     *
     * @param prefix The title prefix to search for. Must not be blank.
     * @param filter Optional [ConversationFilter] to further narrow results.
     * @param limit  Maximum number of results to return. Defaults to 20.
     * @return A list of matching [Conversation] objects ordered by title ascending.
     */
    suspend fun searchConversationsByTitle(
        prefix: String,
        filter: ConversationFilter? = null,
        limit: Long = 20
    ): Result<List<Conversation>> = runCatching {
        require(prefix.isNotBlank()) { "Search prefix must not be blank." }
        val end      = prefix.trimEnd() + "\uf8ff"
        var query: Query = conversationsCollection()
            .whereGreaterThanOrEqualTo(FIELD_TITLE, prefix)
            .whereLessThanOrEqualTo(FIELD_TITLE, end)
            .orderBy(FIELD_TITLE, Query.Direction.ASCENDING)
            .limit(limit)
        filter?.type?.let       { query = query.whereEqualTo(FIELD_TYPE, it.value) }
        filter?.creatorId?.let  { query = query.whereEqualTo(FIELD_CREATOR_ID, it) }
        filter?.translated?.let { query = query.whereEqualTo(FIELD_TRANSLATED, it) }

        query.get().await().toObjects(Conversation::class.java)
    }

    /**
     * Searches conversations by [subtitle] prefix using the same lexicographic
     * range strategy as [searchConversationsByTitle].
     *
     * Requires an ascending index on `subtitle`.
     *
     * @param prefix The subtitle prefix to search for. Must not be blank.
     * @param limit  Maximum number of results to return. Defaults to 20.
     * @return A list of matching [Conversation] objects ordered by subtitle ascending.
     */
    suspend fun searchConversationsBySubtitle(
        prefix: String,
        limit: Long = 20
    ): Result<List<Conversation>> = runCatching {
        require(prefix.isNotBlank()) { "Search prefix must not be blank." }
        val end = prefix.trimEnd() + "\uf8ff"
        conversationsCollection()
            .whereGreaterThanOrEqualTo("subtitle", prefix)
            .whereLessThanOrEqualTo("subtitle", end)
            .orderBy("subtitle", Query.Direction.ASCENDING)
            .limit(limit)
            .get()
            .await()
            .toObjects(Conversation::class.java)
    }

    /**
     * Fetches all conversations created by a specific user, ordered by creation
     * date descending.
     *
     * @param creatorId The Firebase UID of the creator to search for.
     * @param type      Optional participant type filter.
     * @param limit     Maximum number of results to return. Defaults to 20.
     */
    suspend fun searchConversationsByCreator(
        creatorId: String,
        type: ParticipantType? = null,
        limit: Long = 20
    ): Result<List<Conversation>> = runCatching {
        require(creatorId.isNotBlank()) { "creatorId must not be blank." }
        var query: Query = conversationsCollection()
            .whereEqualTo(FIELD_CREATOR_ID, creatorId)
            .orderBy(FIELD_CREATED_AT, Query.Direction.DESCENDING)
            .limit(limit)
        type?.let { query = query.whereEqualTo(FIELD_TYPE, it.value) }
        query.get().await().toObjects(Conversation::class.java)
    }

    /**
     * Searches conversations by [title] prefix in real time, emitting a fresh
     * result list on every Firestore change that affects the matched documents.
     * This is suitable for a live search bar where results update as the user
     * types.
     *
     * The listener is removed automatically when the returned [Flow] is cancelled.
     *
     * @param prefix The title prefix to observe. Must not be blank.
     * @param filter Optional [ConversationFilter] for additional constraints.
     * @param limit  Maximum number of results to stream. Defaults to 20.
     */
    fun observeSearchByTitle(
        prefix: String,
        filter: ConversationFilter? = null,
        limit: Long = 20
    ): Flow<List<Conversation>> = callbackFlow {
        if (prefix.isBlank()) {
            trySend(emptyList())
            awaitClose()
            return@callbackFlow
        }
        val end = prefix.trimEnd() + "\uf8ff"
        var query: Query = conversationsCollection()
            .whereGreaterThanOrEqualTo(FIELD_TITLE, prefix)
            .whereLessThanOrEqualTo(FIELD_TITLE, end)
            .orderBy(FIELD_TITLE, Query.Direction.ASCENDING)
            .limit(limit)
        filter?.type?.let       { query = query.whereEqualTo(FIELD_TYPE, it.value) }
        filter?.creatorId?.let  { query = query.whereEqualTo(FIELD_CREATOR_ID, it) }
        filter?.translated?.let { query = query.whereEqualTo(FIELD_TRANSLATED, it) }

        val registration: ListenerRegistration = query.addSnapshotListener { snapshot, error ->
            if (error != null) { close(error); return@addSnapshotListener }
            trySend(snapshot?.toObjects(Conversation::class.java) ?: emptyList())
        }
        awaitClose { registration.remove() }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Real-Time Listeners
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Emits an updated [Conversation] object whenever the given document changes,
     * or null if the document no longer exists.
     *
     * The underlying [ListenerRegistration] is removed automatically when the
     * returned [Flow] is cancelled.
     *
     * @param conversationId The conversation document ID to observe.
     */
    fun observeConversation(conversationId: String): Flow<Conversation?> = callbackFlow {
        val registration: ListenerRegistration =
            conversationDocument(conversationId).addSnapshotListener { snapshot, error ->
                if (error != null) { close(error); return@addSnapshotListener }
                trySend(snapshot?.toObject(Conversation::class.java))
            }
        awaitClose { registration.remove() }
    }

    /**
     * Emits an updated list of [Conversation] objects whenever any conversation
     * matching the given [ConversationFilter] changes. If no filter is provided,
     * the entire conversations collection is observed.
     *
     * @param filter Optional [ConversationFilter] to narrow the listener query.
     */
    fun observeConversations(
        filter: ConversationFilter? = null
    ): Flow<List<Conversation>> = callbackFlow {
        val baseQuery = conversationsCollection() as Query
        val query     = filter?.applyTo(baseQuery) ?: baseQuery

        val registration: ListenerRegistration = query.addSnapshotListener { snapshot, error ->
            if (error != null) { close(error); return@addSnapshotListener }
            trySend(snapshot?.toObjects(Conversation::class.java) ?: emptyList())
        }
        awaitClose { registration.remove() }
    }

    /**
     * Emits an updated list of conversation IDs whenever the currently
     * authenticated user's participant membership changes — for example, when
     * they join a new conversation or are removed from an existing one.
     *
     * The conversation ID is read from the stored [FIELD_PARENT_ID] field on
     * each matching participant document, rather than derived from the path.
     *
     * Requires a composite Firestore index on (uid, type) for the
     * [PARTICIPANT_SUB] collection group.
     *
     * @param type Participant type filter; defaults to [ParticipantType.PERSONAL].
     * @return A cold [Flow] that emits a fresh list of conversation IDs on every
     *         membership change.
     */
    fun observeCurrentUserConversationIds(
        type: ParticipantType = ParticipantType.PERSONAL
    ): Flow<List<String>> = callbackFlow {
        val currentUserId = auth.currentUser?.uid
            ?: run { close(IllegalStateException("No authenticated user is signed in.")); return@callbackFlow }

        val registration: ListenerRegistration = firestore
            .collectionGroup(PARTICIPANT_SUB)
            .whereEqualTo(FIELD_UID, currentUserId)
            .whereEqualTo(FIELD_TYPE, type.value)
            .addSnapshotListener { snapshot, error ->
                if (error != null) { close(error); return@addSnapshotListener }
                val ids = snapshot?.documents
                    ?.mapNotNull { it.getString(FIELD_PARENT_ID) }  // fixed: read field, not path
                    ?: emptyList()
                trySend(ids)
            }

        awaitClose { registration.remove() }
    }

    /**
     * Emits a fully hydrated list of [Conversation] objects for every conversation
     * the currently authenticated user has joined, updating in real time as their
     * membership or any of the joined conversation documents change.
     *
     * The conversation ID is read from the stored [FIELD_PARENT_ID] field on
     * each matching participant document, rather than derived from the path.
     *
     * The implementation uses two listener layers:
     *  1. A collection group listener on [PARTICIPANT_SUB] to detect membership
     *     changes and resolve the current set of conversation IDs.
     *  2. An individual document snapshot listener for each resolved conversation
     *     ID, so that changes to a conversation's content are also reflected immediately.
     *
     * All inner listeners are replaced atomically whenever the membership set
     * changes, and every listener is removed when the [Flow] is cancelled.
     *
     * Note: For users who belong to a very large number of conversations,
     * consider using [observeCurrentUserConversationIds] combined with
     * [fetchConversationsPaged] to avoid attaching an unbounded number of
     * document listeners simultaneously.
     *
     * @param type Participant type filter; defaults to [ParticipantType.PERSONAL].
     * @return A cold [Flow] that emits an updated list of [Conversation] objects
     *         whenever membership or any joined conversation document changes.
     */
    fun observeCurrentUserConversations(
        type: ParticipantType = ParticipantType.PERSONAL
    ): Flow<List<Conversation>> = callbackFlow {
        val currentUserId = auth.currentUser?.uid
            ?: run { close(IllegalStateException("No authenticated user is signed in.")); return@callbackFlow }

        val conversationSnapshots = mutableMapOf<String, Conversation?>()
        val innerRegistrations    = mutableMapOf<String, ListenerRegistration>()

        fun emitMerged() {
            trySend(conversationSnapshots.values.filterNotNull())
        }

        val membershipRegistration: ListenerRegistration = firestore
            .collectionGroup(PARTICIPANT_SUB)
            .whereEqualTo(FIELD_UID, currentUserId)
            .whereEqualTo(FIELD_TYPE, type.value)
            .addSnapshotListener { snapshot, error ->
                if (error != null) { close(error); return@addSnapshotListener }

                val currentIds = snapshot?.documents
                    ?.mapNotNull { it.getString(FIELD_PARENT_ID) }  // fixed: read field, not path
                    ?.toSet()
                    ?: emptySet()

                val removedIds = innerRegistrations.keys - currentIds
                removedIds.forEach { id ->
                    innerRegistrations.remove(id)?.remove()
                    conversationSnapshots.remove(id)
                }

                val addedIds = currentIds - innerRegistrations.keys
                addedIds.forEach { conversationId ->
                    val reg = conversationDocument(conversationId)
                        .addSnapshotListener { docSnapshot, docError ->
                            if (docError != null) { close(docError); return@addSnapshotListener }
                            conversationSnapshots[conversationId] =
                                docSnapshot?.toObject(Conversation::class.java)
                            emitMerged()
                        }
                    innerRegistrations[conversationId] = reg
                }

                if (addedIds.isEmpty()) emitMerged()
            }

        awaitClose {
            membershipRegistration.remove()
            innerRegistrations.values.forEach { it.remove() }
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Paging3 Support
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Returns a [Flow] of cursor-paginated [PagingData] over the conversations
     * collection, ordered by [FIELD_UPDATED_AT] descending so the most recently
     * active conversations appear first.
     *
     * @param pageSize Number of documents to load per page.
     */
    fun fetchConversationsPaged(
        pageSize: Int = PAGE_SIZE
    ): Flow<PagingData<Conversation>> = Pager(
        config = PagingConfig(
            pageSize           = pageSize,
            enablePlaceholders = false,
            prefetchDistance   = pageSize / 2
        ),
        pagingSourceFactory = {
            ConversationPagingSource(
                query = conversationsCollection()
                    .orderBy(FIELD_UPDATED_AT, Query.Direction.DESCENDING)
                    .limit(pageSize.toLong())
            )
        }
    ).flow

    /**
     * Returns a [Flow] of cursor-paginated [PagingData] applying a
     * [ConversationFilter], ordered by [FIELD_UPDATED_AT] descending.
     *
     * @param filter   The [ConversationFilter] to apply.
     * @param pageSize Number of documents to load per page.
     */
    fun fetchConversationsFilteredPaged(
        filter: ConversationFilter,
        pageSize: Int = PAGE_SIZE
    ): Flow<PagingData<Conversation>> = Pager(
        config = PagingConfig(
            pageSize           = pageSize,
            enablePlaceholders = false,
            prefetchDistance   = pageSize / 2
        ),
        pagingSourceFactory = {
            ConversationPagingSource(
                query = filter.applyTo(conversationsCollection())
                    .limit(pageSize.toLong())
            )
        }
    ).flow
}

// ─────────────────────────────────────────────────────────────────────────────
// ConversationFilter
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A composable, immutable filter descriptor for conversation queries.
 *
 * Each field is optional. Only non-null fields are applied to the Firestore
 * query, so any combination of constraints is valid. Combining multiple fields
 * on the same query may require a composite Firestore index.
 *
 * @param type          Filters by [ParticipantType].
 * @param creatorId     Filters by the creator's Firebase UID.
 * @param translated    Filters by the translated flag.
 * @param createdAfter  Includes only conversations created after this [Timestamp].
 * @param createdBefore Includes only conversations created before this [Timestamp].
 * @param updatedAfter  Includes only conversations updated after this [Timestamp].
 * @param sortBy        The field name to sort results by; defaults to "updated_at".
 * @param sortOrder     Sort direction; defaults to [Query.Direction.DESCENDING].
 * @param limit         Caps the result set to the given number of documents.
 */
data class ConversationFilter(
    val type: ParticipantType? = null,
    val creatorId: String? = null,
    val translated: Boolean? = null,
    val createdAfter: Timestamp? = null,
    val createdBefore: Timestamp? = null,
    val updatedAfter: Timestamp? = null,
    val sortBy: String = "updated_at",
    val sortOrder: Query.Direction = Query.Direction.DESCENDING,
    val limit: Long? = null
) {

    companion object {
        /** All personal conversations, most recently updated first. */
        val PERSONAL = ConversationFilter(type = ParticipantType.PERSONAL)

        /** All group conversations, most recently updated first. */
        val GROUP = ConversationFilter(type = ParticipantType.GROUP)
    }

    fun applyTo(query: Query): Query {
        var q = query

        type?.let          { q = q.whereEqualTo("type", it.value) }
        creatorId?.let     { q = q.whereEqualTo("creator_id", it) }
        translated?.let    { q = q.whereEqualTo("translated", it) }
        createdAfter?.let  { q = q.whereGreaterThan("created_at", it) }
        createdBefore?.let { q = q.whereLessThan("created_at", it) }
        updatedAfter?.let  { q = q.whereGreaterThan("updated_at", it) }

        q = q.orderBy(sortBy, sortOrder)

        limit?.let { q = q.limit(it) }

        return q
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// ConversationPagingSource
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A Firestore-backed [PagingSource] for [Conversation] documents.
 *
 * Uses cursor-based pagination via [DocumentSnapshot.startAfter] to avoid
 * re-reading previously loaded pages. Only forward pagination is supported;
 * refreshes always restart from the first page.
 *
 * @param query The base Firestore [Query] — must include a [Query.limit] clause.
 */
class ConversationPagingSource(
    private val query: Query
) : PagingSource<DocumentSnapshot, Conversation>() {

    override suspend fun load(
        params: LoadParams<DocumentSnapshot>
    ): LoadResult<DocumentSnapshot, Conversation> = try {
        val pageQuery     = params.key?.let { query.startAfter(it) } ?: query
        val snapshot      = pageQuery.get().await()
        val conversations = snapshot.toObjects(Conversation::class.java)
        val nextKey       = snapshot.documents.lastOrNull().takeUnless { snapshot.isEmpty }

        LoadResult.Page(data = conversations, prevKey = null, nextKey = nextKey)
    } catch (e: Exception) {
        LoadResult.Error(e)
    }

    override fun getRefreshKey(
        state: PagingState<DocumentSnapshot, Conversation>
    ): DocumentSnapshot? = null
}